title: Kaiteki
description: "The comfy SNS client for everything, everywhere."
permalink: /posts/:categories/:year/:month/:day/:title/
plugins: [jekyll-feed]
links:
  fediverse: https://fedi.software/@Kaiteki
  telegram: kaiteki_fedi
  matrix: '#kaiteki:fedibird.com'
  git: https://github.com/Kaiteki-Fedi/Kaiteki/
  weblate: https://hosted.weblate.org/projects/kaiteki/

sass:
  style: compressed
exclude: [README.md, LICENSE]

defaults:
  -
    scope:
      path: ""
      type: "help"
    values:
      layout: "help"
  -
    scope:
      path: ""
      type: "compatibility"
    values:
      layout: "backend-compatibility"

collections:
  help:
    output: true
  compatibility:
    output: true

