title: Kaiteki
baseurl: "https://craftplacer.moe/projects/kaiteki"
url: "https://craftplacer.moe/projects/kaiteki"
# paginate: 10
permalink: /posts/:categories/:year/:month/:day/:title/
plugins: [jekyll-feed]
sass:
  style: compressed

defaults:
  -
    scope:
      path: ""
      type: "help"
    values:
      layout: "help"

collections:
  help:
    output: true